version: "3.9"

services:
  api:
    build: .
    container_name: deepseek_api
    ports:
      - "8000:8000"
    # Keep secrets in .env (do NOT hardcode tokens here)
    environment:
      # Example: - HF_API_KEY (set via .env or CI secrets)
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: deepseek_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deepseek
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: deepseek_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
version: "3.9"

services:
  api:
    build: .
    container_name: deepseek_api
    ports:
      - "8000:8000"
    environment:
      # - HF_API_KEY=<REDACTED or set via .env>
    # Use env_file (.env) for sensitive variables like HF_API_KEY / HUGGINGFACE_API_KEY
    # environment:
    #   - DEEPSEEK_API_KEY=sk-e5f6da5d1c2e46b1994eb5a23782d5ab
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: deepseek_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deepseek
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: deepseek_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
